### ISSUE TITLE
spinning taxi svg is static

### ISSUE THREAD

**Issue by simonpcouch** [tidymodels/workshops#155] opened 2023-07-11 15:20 UTC
Locally and via workshops.tidymodels.org, I see the spinning wheels on the taxi, but I don't see that effect on the shared slides.

**Comment by simonpcouch** [comment] 2023-07-11 15:21
Oh, I do—it just updates every second or two🤔

**Comment by EmilHvitfeldt** [comment] 2023-07-26 22:00
I did some more research and I was not able to reproduce this anymore. Maybe we are all good. Closing for now

**Closed by EmilHvitfeldt** 2023-07-26 22:00 UTC
Labels: 2023 Conf, Intro, Advanced
